@GoogleOAuthPrototype_Application_HostAddress = http://localhost:5080
@BearerToken = TOKEN
@RefreshToken = REFRESH_TOKEN

GET {{GoogleOAuthPrototype_Application_HostAddress}}/health/
Accept: application/json

###

GET {{GoogleOAuthPrototype_Application_HostAddress}}/api/generate-url?accessType=offline&prompt=consent
Accept: application/json

###

GET {{GoogleOAuthPrototype_Application_HostAddress}}/api/google-auth-callback/
Accept: application/json

###

GET {{GoogleOAuthPrototype_Application_HostAddress}}/api/get-tokens?code=4/0ASVgi3JEc6cWk251l497d-bKR5byrLE59Pue8RIkSYjfOYvOCv4qRBl9De6CeMnlNphYpg
Accept: application/json

###

GET {{GoogleOAuthPrototype_Application_HostAddress}}/api/get-user-data
Accept: application/json
Authorization: Bearer {{BearerToken}}

###

GET {{GoogleOAuthPrototype_Application_HostAddress}}/api/revoke-token?token={{BearerToken}}
Accept: application/json

###

GET {{GoogleOAuthPrototype_Application_HostAddress}}/api/refresh-token?refreshToken={{RefreshToken}}
Accept: application/json

###